/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DIDRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "registerDID"
      | "resolveDID"
      | "transferOwnership"
      | "updatePublicKey"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DIDOwnershipTransferred"
      | "DIDPublicKeyUpdated"
      | "DIDRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "registerDID",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDID",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePublicKey",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "registerDID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "resolveDID", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePublicKey",
    data: BytesLike
  ): Result;
}

export namespace DIDOwnershipTransferredEvent {
  export type InputTuple = [
    didHash: BytesLike,
    previousController: AddressLike,
    newController: AddressLike
  ];
  export type OutputTuple = [
    didHash: string,
    previousController: string,
    newController: string
  ];
  export interface OutputObject {
    didHash: string;
    previousController: string;
    newController: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDPublicKeyUpdatedEvent {
  export type InputTuple = [didHash: BytesLike, newPublicKey: BytesLike];
  export type OutputTuple = [didHash: string, newPublicKey: string];
  export interface OutputObject {
    didHash: string;
    newPublicKey: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DIDRegisteredEvent {
  export type InputTuple = [didHash: BytesLike, controller: AddressLike];
  export type OutputTuple = [didHash: string, controller: string];
  export interface OutputObject {
    didHash: string;
    controller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DIDRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DIDRegistry;
  waitForDeployment(): Promise<this>;

  interface: DIDRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  registerDID: TypedContractMethod<
    [didHash: BytesLike, publicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  resolveDID: TypedContractMethod<
    [didHash: BytesLike],
    [
      [string, string, bigint] & {
        controller: string;
        publicKey: string;
        updatedAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [didHash: BytesLike, newController: AddressLike],
    [void],
    "nonpayable"
  >;

  updatePublicKey: TypedContractMethod<
    [didHash: BytesLike, publicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "registerDID"
  ): TypedContractMethod<
    [didHash: BytesLike, publicKey: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDID"
  ): TypedContractMethod<
    [didHash: BytesLike],
    [
      [string, string, bigint] & {
        controller: string;
        publicKey: string;
        updatedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<
    [didHash: BytesLike, newController: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePublicKey"
  ): TypedContractMethod<
    [didHash: BytesLike, publicKey: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DIDOwnershipTransferred"
  ): TypedContractEvent<
    DIDOwnershipTransferredEvent.InputTuple,
    DIDOwnershipTransferredEvent.OutputTuple,
    DIDOwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "DIDPublicKeyUpdated"
  ): TypedContractEvent<
    DIDPublicKeyUpdatedEvent.InputTuple,
    DIDPublicKeyUpdatedEvent.OutputTuple,
    DIDPublicKeyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DIDRegistered"
  ): TypedContractEvent<
    DIDRegisteredEvent.InputTuple,
    DIDRegisteredEvent.OutputTuple,
    DIDRegisteredEvent.OutputObject
  >;

  filters: {
    "DIDOwnershipTransferred(bytes32,address,address)": TypedContractEvent<
      DIDOwnershipTransferredEvent.InputTuple,
      DIDOwnershipTransferredEvent.OutputTuple,
      DIDOwnershipTransferredEvent.OutputObject
    >;
    DIDOwnershipTransferred: TypedContractEvent<
      DIDOwnershipTransferredEvent.InputTuple,
      DIDOwnershipTransferredEvent.OutputTuple,
      DIDOwnershipTransferredEvent.OutputObject
    >;

    "DIDPublicKeyUpdated(bytes32,bytes)": TypedContractEvent<
      DIDPublicKeyUpdatedEvent.InputTuple,
      DIDPublicKeyUpdatedEvent.OutputTuple,
      DIDPublicKeyUpdatedEvent.OutputObject
    >;
    DIDPublicKeyUpdated: TypedContractEvent<
      DIDPublicKeyUpdatedEvent.InputTuple,
      DIDPublicKeyUpdatedEvent.OutputTuple,
      DIDPublicKeyUpdatedEvent.OutputObject
    >;

    "DIDRegistered(bytes32,address)": TypedContractEvent<
      DIDRegisteredEvent.InputTuple,
      DIDRegisteredEvent.OutputTuple,
      DIDRegisteredEvent.OutputObject
    >;
    DIDRegistered: TypedContractEvent<
      DIDRegisteredEvent.InputTuple,
      DIDRegisteredEvent.OutputTuple,
      DIDRegisteredEvent.OutputObject
    >;
  };
}
