/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DIDRegistry } from "./DIDRegistry";
export type { RevocationRegistry } from "./RevocationRegistry";
export type { TrustedIssuerRegistry } from "./TrustedIssuerRegistry";
export * as factories from "./factories";
export { DIDRegistry__factory } from "./factories/DIDRegistry__factory";
export { RevocationRegistry__factory } from "./factories/RevocationRegistry__factory";
export { TrustedIssuerRegistry__factory } from "./factories/TrustedIssuerRegistry__factory";
