/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface RevocationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "anchorCredential"
      | "getCredentialStatus"
      | "revokeCredential"
      | "tir"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "CredentialAnchored" | "CredentialRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "anchorCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCredentialStatus",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeCredential",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "tir", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "anchorCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCredentialStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeCredential",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "tir", data: BytesLike): Result;
}

export namespace CredentialAnchoredEvent {
  export type InputTuple = [credentialHash: BytesLike, issuer: AddressLike];
  export type OutputTuple = [credentialHash: string, issuer: string];
  export interface OutputObject {
    credentialHash: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CredentialRevokedEvent {
  export type InputTuple = [credentialHash: BytesLike, issuer: AddressLike];
  export type OutputTuple = [credentialHash: string, issuer: string];
  export interface OutputObject {
    credentialHash: string;
    issuer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface RevocationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): RevocationRegistry;
  waitForDeployment(): Promise<this>;

  interface: RevocationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  anchorCredential: TypedContractMethod<
    [credentialHash: BytesLike],
    [void],
    "nonpayable"
  >;

  getCredentialStatus: TypedContractMethod<
    [credentialHash: BytesLike],
    [
      [boolean, boolean, boolean, string, bigint] & {
        isAnchored: boolean;
        isRevoked: boolean;
        issuerStillTrusted: boolean;
        issuer: string;
        anchoredAt: bigint;
      }
    ],
    "view"
  >;

  revokeCredential: TypedContractMethod<
    [credentialHash: BytesLike],
    [void],
    "nonpayable"
  >;

  tir: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "anchorCredential"
  ): TypedContractMethod<[credentialHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getCredentialStatus"
  ): TypedContractMethod<
    [credentialHash: BytesLike],
    [
      [boolean, boolean, boolean, string, bigint] & {
        isAnchored: boolean;
        isRevoked: boolean;
        issuerStillTrusted: boolean;
        issuer: string;
        anchoredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeCredential"
  ): TypedContractMethod<[credentialHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "tir"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "CredentialAnchored"
  ): TypedContractEvent<
    CredentialAnchoredEvent.InputTuple,
    CredentialAnchoredEvent.OutputTuple,
    CredentialAnchoredEvent.OutputObject
  >;
  getEvent(
    key: "CredentialRevoked"
  ): TypedContractEvent<
    CredentialRevokedEvent.InputTuple,
    CredentialRevokedEvent.OutputTuple,
    CredentialRevokedEvent.OutputObject
  >;

  filters: {
    "CredentialAnchored(bytes32,address)": TypedContractEvent<
      CredentialAnchoredEvent.InputTuple,
      CredentialAnchoredEvent.OutputTuple,
      CredentialAnchoredEvent.OutputObject
    >;
    CredentialAnchored: TypedContractEvent<
      CredentialAnchoredEvent.InputTuple,
      CredentialAnchoredEvent.OutputTuple,
      CredentialAnchoredEvent.OutputObject
    >;

    "CredentialRevoked(bytes32,address)": TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
    CredentialRevoked: TypedContractEvent<
      CredentialRevokedEvent.InputTuple,
      CredentialRevokedEvent.OutputTuple,
      CredentialRevokedEvent.OutputObject
    >;
  };
}
